name: CICD Pipeline
on:
  push:
    branches:
      - develop
jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          python-version: '3.12' 
      - run: pip install requirements.txt